# encoding: latin-1

import pandas as pd
pd.options.display.width = 220
pd.options.display.precision = 6

import numpy as np
import sqlite3
from .data_handling import filterChromByLabels, check_sqlite_table
from .std_logger import logging
from .report import plot_scores

def export_tsv(infile, outfile, format, outcsv, transition_quantification, ipf, max_rs_peakgroup_qvalue, peptide, max_global_peptide_qvalue, protein, max_global_protein_qvalue):

    con = sqlite3.connect(infile)

    ipf_present = False
    if ipf:
        ipf_present = check_sqlite_table(con, "SCORE_IPF")

    if ipf_present and ipf:
        if transition_quantification:
            data = pd.read_sql_query("SELECT RUN.ID AS ID_RUN, PEPTIDE.ID AS ID_PEPTIDE, PEPTIDE_IPF.MODIFIED_SEQUENCE || '_' || PRECURSOR.ID AS TRANSITION_GROUP_ID, PRECURSOR.DECOY AS DECOY, RUN.ID AS RUN_ID, RUN.FILENAME AS FILENAME, FEATURE.EXP_RT AS RT, FEATURE.NORM_RT AS IRT, FEATURE.ID AS ID, PEPTIDE_IPF.UNMODIFIED_SEQUENCE AS SEQUENCE, PEPTIDE_IPF.MODIFIED_SEQUENCE AS FULLUNIMODPEPTIDENAME, PRECURSOR.CHARGE AS CHARGE, PRECURSOR.PRECURSOR_MZ AS MZ, FEATURE_MS2.AREA_INTENSITY AS INTENSITY, FEATURE_MS1.AREA_INTENSITY AS AGGR_PREC_PEAK_AREA, FEATURE_MS1.APEX_INTENSITY AS AGGR_PREC_PEAK_APEX, AGGR_PEAK_AREA, AGGR_PEAK_APEX, AGGR_FRAGMENT_ANNOTATION, PRECURSOR.LIBRARY_RT AS ASSAY_RT, FEATURE.DELTA_RT AS DELTA_RT, FEATURE.LEFT_WIDTH AS LEFTWIDTH, FEATURE.RIGHT_WIDTH AS RIGHTWIDTH, SCORE_MS1.PEP AS MS1_PEP, SCORE_MS2.PEP AS MS2_PEP, SCORE_IPF.PRECURSOR_PEAKGROUP_PEP AS PRECURSOR_PEP, SCORE_IPF.PEP AS IPF_PEP, SCORE_MS2.SCORE AS D_SCORE, SCORE_MS2.QVALUE AS MS2_M_SCORE, SCORE_IPF.QVALUE AS M_SCORE FROM PRECURSOR JOIN PRECURSOR_PEPTIDE_MAPPING ON PRECURSOR.ID = PRECURSOR_PEPTIDE_MAPPING.PRECURSOR_ID JOIN PEPTIDE ON PRECURSOR_PEPTIDE_MAPPING.PEPTIDE_ID = PEPTIDE.ID INNER JOIN FEATURE ON FEATURE.PRECURSOR_ID = PRECURSOR.ID JOIN RUN ON RUN.ID = FEATURE.RUN_ID JOIN FEATURE_MS1 ON FEATURE_MS1.FEATURE_ID = FEATURE.ID JOIN FEATURE_MS2 ON FEATURE_MS2.FEATURE_ID = FEATURE.ID JOIN (SELECT FEATURE_ID, GROUP_CONCAT(AREA_INTENSITY,';') AS AGGR_PEAK_AREA, GROUP_CONCAT(APEX_INTENSITY,';') AS AGGR_PEAK_APEX, GROUP_CONCAT(TRANSITION_ID,';') AS AGGR_FRAGMENT_ANNOTATION FROM FEATURE_TRANSITION INNER JOIN TRANSITION ON FEATURE_TRANSITION.TRANSITION_ID = TRANSITION.ID WHERE TRANSITION.DECOY == 0 GROUP BY FEATURE_ID) AS FEATURE_TRANSITION ON FEATURE_TRANSITION.FEATURE_ID = FEATURE.ID JOIN SCORE_MS1 ON SCORE_MS1.FEATURE_ID = FEATURE.ID JOIN SCORE_MS2 ON SCORE_MS2.FEATURE_ID = FEATURE.ID JOIN SCORE_IPF ON SCORE_IPF.FEATURE_ID = FEATURE.ID JOIN PEPTIDE AS PEPTIDE_IPF ON SCORE_IPF.PEPTIDE_ID = PEPTIDE_IPF.ID;", con)
        else:
            data = pd.read_sql_query("SELECT RUN.ID AS ID_RUN, PEPTIDE.ID AS ID_PEPTIDE, PEPTIDE_IPF.MODIFIED_SEQUENCE || '_' || PRECURSOR.ID AS TRANSITION_GROUP_ID, PRECURSOR.DECOY AS DECOY, RUN.ID AS RUN_ID, RUN.FILENAME AS FILENAME, FEATURE.EXP_RT AS RT, FEATURE.NORM_RT AS IRT, FEATURE.ID AS ID, PEPTIDE_IPF.UNMODIFIED_SEQUENCE AS SEQUENCE, PEPTIDE_IPF.MODIFIED_SEQUENCE AS FULLUNIMODPEPTIDENAME, PRECURSOR.CHARGE AS CHARGE, PRECURSOR.PRECURSOR_MZ AS MZ, FEATURE_MS2.AREA_INTENSITY AS INTENSITY, FEATURE_MS1.AREA_INTENSITY AS AGGR_PREC_PEAK_AREA, FEATURE_MS1.APEX_INTENSITY AS AGGR_PREC_PEAK_APEX, PRECURSOR.LIBRARY_RT AS ASSAY_RT, FEATURE.DELTA_RT AS DELTA_RT, FEATURE.LEFT_WIDTH AS LEFTWIDTH, FEATURE.RIGHT_WIDTH AS RIGHTWIDTH, SCORE_MS1.PEP AS MS1_PEP, SCORE_MS2.PEP AS MS2_PEP, SCORE_IPF.PRECURSOR_PEAKGROUP_PEP AS PRECURSOR_PEP, SCORE_IPF.PEP AS IPF_PEP, SCORE_MS2.SCORE AS D_SCORE, SCORE_MS2.QVALUE AS MS2_M_SCORE, SCORE_IPF.QVALUE AS M_SCORE FROM PRECURSOR JOIN PRECURSOR_PEPTIDE_MAPPING ON PRECURSOR.ID = PRECURSOR_PEPTIDE_MAPPING.PRECURSOR_ID JOIN PEPTIDE ON PRECURSOR_PEPTIDE_MAPPING.PEPTIDE_ID = PEPTIDE.ID INNER JOIN FEATURE ON FEATURE.PRECURSOR_ID = PRECURSOR.ID JOIN RUN ON RUN.ID = FEATURE.RUN_ID JOIN FEATURE_MS1 ON FEATURE_MS1.FEATURE_ID = FEATURE.ID JOIN FEATURE_MS2 ON FEATURE_MS2.FEATURE_ID = FEATURE.ID JOIN SCORE_MS1 ON SCORE_MS1.FEATURE_ID = FEATURE.ID JOIN SCORE_MS2 ON SCORE_MS2.FEATURE_ID = FEATURE.ID JOIN SCORE_IPF ON SCORE_IPF.FEATURE_ID = FEATURE.ID JOIN PEPTIDE AS PEPTIDE_IPF ON SCORE_IPF.PEPTIDE_ID = PEPTIDE_IPF.ID;", con)

    else:
        if transition_quantification:
            data = pd.read_sql_query("SELECT RUN.ID AS ID_RUN, PEPTIDE.ID AS ID_PEPTIDE, PRECURSOR.ID AS TRANSITION_GROUP_ID, PRECURSOR.DECOY AS DECOY, RUN.ID AS RUN_ID, RUN.FILENAME AS FILENAME, FEATURE.EXP_RT AS RT, FEATURE.NORM_RT AS IRT, FEATURE.ID AS ID, PEPTIDE.UNMODIFIED_SEQUENCE AS SEQUENCE, PEPTIDE.MODIFIED_SEQUENCE AS FULLUNIMODPEPTIDENAME, PRECURSOR.CHARGE AS CHARGE, PRECURSOR.PRECURSOR_MZ AS MZ, FEATURE_MS2.AREA_INTENSITY AS INTENSITY, FEATURE_MS1.AREA_INTENSITY AS AGGR_PREC_PEAK_AREA, FEATURE_MS1.APEX_INTENSITY AS AGGR_PREC_PEAK_APEX, AGGR_PEAK_AREA, AGGR_PEAK_APEX, AGGR_FRAGMENT_ANNOTATION, PRECURSOR.LIBRARY_RT AS ASSAY_RT, FEATURE.DELTA_RT AS DELTA_RT, FEATURE.LEFT_WIDTH AS LEFTWIDTH, FEATURE.RIGHT_WIDTH AS RIGHTWIDTH, SCORE_MS2.SCORE AS D_SCORE, SCORE_MS2.QVALUE AS M_SCORE FROM PRECURSOR JOIN PRECURSOR_PEPTIDE_MAPPING ON PRECURSOR.ID = PRECURSOR_PEPTIDE_MAPPING.PRECURSOR_ID JOIN PEPTIDE ON PRECURSOR_PEPTIDE_MAPPING.PEPTIDE_ID = PEPTIDE.ID INNER JOIN FEATURE ON FEATURE.PRECURSOR_ID = PRECURSOR.ID JOIN RUN ON RUN.ID = FEATURE.RUN_ID JOIN FEATURE_MS1 ON FEATURE_MS1.FEATURE_ID = FEATURE.ID JOIN FEATURE_MS2 ON FEATURE_MS2.FEATURE_ID = FEATURE.ID JOIN (SELECT FEATURE_ID, GROUP_CONCAT(AREA_INTENSITY,';') AS AGGR_PEAK_AREA, GROUP_CONCAT(APEX_INTENSITY,';') AS AGGR_PEAK_APEX, GROUP_CONCAT(TRANSITION_ID,';') AS AGGR_FRAGMENT_ANNOTATION FROM FEATURE_TRANSITION INNER JOIN TRANSITION ON FEATURE_TRANSITION.TRANSITION_ID = TRANSITION.ID GROUP BY FEATURE_ID) AS FEATURE_TRANSITION ON FEATURE_TRANSITION.FEATURE_ID = FEATURE.ID JOIN SCORE_MS2 ON SCORE_MS2.FEATURE_ID = FEATURE.ID;", con)
        else:
            data = pd.read_sql_query("SELECT RUN.ID AS ID_RUN, PEPTIDE.ID AS ID_PEPTIDE, PRECURSOR.ID AS TRANSITION_GROUP_ID, PRECURSOR.DECOY AS DECOY, RUN.ID AS RUN_ID, RUN.FILENAME AS FILENAME, FEATURE.EXP_RT AS RT, FEATURE.NORM_RT AS IRT, FEATURE.ID AS ID, PEPTIDE.UNMODIFIED_SEQUENCE AS SEQUENCE, PEPTIDE.MODIFIED_SEQUENCE AS FULLUNIMODPEPTIDENAME, PRECURSOR.CHARGE AS CHARGE, PRECURSOR.PRECURSOR_MZ AS MZ, FEATURE_MS2.AREA_INTENSITY AS INTENSITY, FEATURE_MS1.AREA_INTENSITY AS AGGR_PREC_PEAK_AREA, FEATURE_MS1.APEX_INTENSITY AS AGGR_PREC_PEAK_APEX, PRECURSOR.LIBRARY_RT AS ASSAY_RT, FEATURE.DELTA_RT AS DELTA_RT, FEATURE.LEFT_WIDTH AS LEFTWIDTH, FEATURE.RIGHT_WIDTH AS RIGHTWIDTH, SCORE_MS2.SCORE AS D_SCORE, SCORE_MS2.QVALUE AS M_SCORE FROM PRECURSOR JOIN PRECURSOR_PEPTIDE_MAPPING ON PRECURSOR.ID = PRECURSOR_PEPTIDE_MAPPING.PRECURSOR_ID JOIN PEPTIDE ON PRECURSOR_PEPTIDE_MAPPING.PEPTIDE_ID = PEPTIDE.ID INNER JOIN FEATURE ON FEATURE.PRECURSOR_ID = PRECURSOR.ID JOIN RUN ON RUN.ID = FEATURE.RUN_ID JOIN FEATURE_MS1 ON FEATURE_MS1.FEATURE_ID = FEATURE.ID JOIN FEATURE_MS2 ON FEATURE_MS2.FEATURE_ID = FEATURE.ID JOIN SCORE_MS2 ON SCORE_MS2.FEATURE_ID = FEATURE.ID;", con)

    # Append concatenated protein identifier
    data_protein = pd.read_sql_query("SELECT PEPTIDE_ID AS ID_PEPTIDE, GROUP_CONCAT(PROTEIN.PROTEIN_ACCESSION,';') AS PROTEINNAME FROM PEPTIDE_PROTEIN_MAPPING INNER JOIN PROTEIN ON PEPTIDE_PROTEIN_MAPPING.PROTEIN_ID = PROTEIN.ID GROUP BY PEPTIDE_ID;", con)
    data = pd.merge(data, data_protein, how='inner', on=['id_peptide'])

    # Append peptide error-rate control
    peptide_present = False
    if peptide:
        peptide_present = check_sqlite_table(con, "SCORE_PEPTIDE")

    if peptide_present and peptide:
        data_peptide_run = pd.read_sql_query("SELECT RUN_ID AS ID_RUN, PEPTIDE_ID AS ID_PEPTIDE, QVALUE AS M_SCORE_PEPTIDE_RUN_SPECIFIC FROM SCORE_PEPTIDE WHERE CONTEXT == 'run-specific';", con)
        if len(data_peptide_run.index) > 0:
            data = pd.merge(data, data_peptide_run, how='inner', on=['id_run','id_peptide'])

        data_peptide_experiment = pd.read_sql_query("SELECT RUN_ID AS ID_RUN, PEPTIDE_ID AS ID_PEPTIDE, QVALUE AS M_SCORE_PEPTIDE_EXPERIMENT_WIDE FROM SCORE_PEPTIDE WHERE CONTEXT == 'experiment-wide';", con)
        if len(data_peptide_experiment.index) > 0:
            data = pd.merge(data, data_peptide_experiment, on=['id_run','id_peptide'])

        data_peptide_global = pd.read_sql_query("SELECT PEPTIDE_ID AS ID_PEPTIDE, QVALUE AS M_SCORE_PEPTIDE_GLOBAL FROM SCORE_PEPTIDE WHERE CONTEXT == 'global';", con)
        if len(data_peptide_global.index) > 0:
            data = pd.merge(data, data_peptide_global[data_peptide_global['m_score_peptide_global'] < max_global_peptide_qvalue], on=['id_peptide'])

    # Append protein error-rate control
    protein_present = False
    if protein:
        protein_present = check_sqlite_table(con, "SCORE_PROTEIN")

    if protein_present and protein:
        data_protein_run = pd.read_sql_query("SELECT RUN_ID AS ID_RUN, PEPTIDE_ID AS ID_PEPTIDE, MIN(QVALUE) AS M_SCORE_PROTEIN_RUN_SPECIFIC FROM PEPTIDE_PROTEIN_MAPPING INNER JOIN SCORE_PROTEIN ON PEPTIDE_PROTEIN_MAPPING.PROTEIN_ID = SCORE_PROTEIN.PROTEIN_ID WHERE CONTEXT == 'run-specific' GROUP BY RUN_ID, PEPTIDE_ID;", con)
        if len(data_protein_run.index) > 0:
            data = pd.merge(data, data_protein_run, how='inner', on=['id_run','id_peptide'])

        data_protein_experiment = pd.read_sql_query("SELECT RUN_ID AS ID_RUN, PEPTIDE_ID AS ID_PEPTIDE, MIN(QVALUE) AS M_SCORE_PROTEIN_EXPERIMENT_WIDE FROM PEPTIDE_PROTEIN_MAPPING INNER JOIN SCORE_PROTEIN ON PEPTIDE_PROTEIN_MAPPING.PROTEIN_ID = SCORE_PROTEIN.PROTEIN_ID WHERE CONTEXT == 'experiment-wide' GROUP BY RUN_ID, PEPTIDE_ID;", con)
        if len(data_protein_experiment.index) > 0:
            data = pd.merge(data, data_protein_experiment, how='inner', on=['id_run','id_peptide'])

        data_protein_global = pd.read_sql_query("SELECT PEPTIDE_ID AS ID_PEPTIDE, MIN(QVALUE) AS M_SCORE_PROTEIN_GLOBAL FROM PEPTIDE_PROTEIN_MAPPING INNER JOIN SCORE_PROTEIN ON PEPTIDE_PROTEIN_MAPPING.PROTEIN_ID = SCORE_PROTEIN.PROTEIN_ID WHERE CONTEXT == 'global' GROUP BY PEPTIDE_ID;", con)
        if len(data_protein_global.index) > 0:
            data = pd.merge(data, data_protein_global[data_protein_global['m_score_protein_global'] < max_global_protein_qvalue], how='inner', on=['id_peptide'])

    if outcsv:
        sep = ","
    else:
        sep = "\t"

    if format == 'legacy':
        data.drop(['id_run','id_peptide'], axis=1).to_csv(outfile, sep=sep, index=False)
    elif format == 'matrix':
        # select top ranking peak group only
        data = data.iloc[data.groupby(['run_id','transition_group_id']).apply(lambda x: x['m_score'].idxmin())]
        # limit peak groups to q-value cutoff
        data = data[data['m_score'] < max_rs_peakgroup_qvalue]
        # restructure dataframe to matrix
        data = data[['transition_group_id','Sequence','FullUniModPeptideName','ProteinName','filename','Intensity']]
        data = data.pivot_table(index=['transition_group_id','Sequence','FullUniModPeptideName','ProteinName'], columns='filename', values='Intensity')
        data.to_csv(outfile, sep=sep, index=True)

    con.close()

def export_score_plots(infile):

    con = sqlite3.connect(infile)

    if check_sqlite_table(con, "SCORE_MS2"):
        outfile = infile.split(".osw")[0] + "_ms2_score_plots.pdf"
        table_ms2 = pd.read_sql_query("SELECT *, RUN_ID || '_' || PRECURSOR_ID AS GROUP_ID, VAR_XCORR_SHAPE AS MAIN_VAR_XCORR_SHAPE FROM FEATURE_MS2 INNER JOIN (SELECT RUN_ID, ID, PRECURSOR_ID, EXP_RT FROM FEATURE) AS FEATURE ON FEATURE_MS2.FEATURE_ID = FEATURE.ID INNER JOIN (SELECT ID, DECOY FROM PRECURSOR) AS PRECURSOR ON FEATURE.PRECURSOR_ID = PRECURSOR.ID INNER JOIN SCORE_MS2 ON FEATURE.ID = SCORE_MS2.FEATURE_ID WHERE RANK == 1 ORDER BY RUN_ID, PRECURSOR.ID ASC, FEATURE.EXP_RT ASC;", con)
        plot_scores(table_ms2, outfile)

    if check_sqlite_table(con, "SCORE_MS1"):
        outfile = infile.split(".osw")[0] + "_ms1_score_plots.pdf"
        table_ms1 = pd.read_sql_query("SELECT *, RUN_ID || '_' || PRECURSOR_ID AS GROUP_ID, VAR_XCORR_SHAPE AS MAIN_VAR_XCORR_SHAPE FROM FEATURE_MS1 INNER JOIN (SELECT RUN_ID, ID, PRECURSOR_ID, EXP_RT FROM FEATURE) AS FEATURE ON FEATURE_MS1.FEATURE_ID = FEATURE.ID INNER JOIN (SELECT ID, DECOY FROM PRECURSOR) AS PRECURSOR ON FEATURE.PRECURSOR_ID = PRECURSOR.ID INNER JOIN SCORE_MS1 ON FEATURE.ID = SCORE_MS1.FEATURE_ID WHERE RANK == 1 ORDER BY RUN_ID, PRECURSOR.ID ASC, FEATURE.EXP_RT ASC;", con)
        plot_scores(table_ms1, outfile)

    if check_sqlite_table(con, "SCORE_TRANSITION"):
        outfile = infile.split(".osw")[0] + "_transition_score_plots.pdf"
        table_transition = pd.read_sql_query("SELECT TRANSITION.DECOY AS DECOY, FEATURE_TRANSITION.*, SCORE_TRANSITION.*, RUN_ID || '_' || FEATURE_TRANSITION.FEATURE_ID || '_' || PRECURSOR_ID || '_' || FEATURE_TRANSITION.TRANSITION_ID AS GROUP_ID, VAR_XCORR_SHAPE AS MAIN_VAR_XCORR_SHAPE FROM FEATURE_TRANSITION INNER JOIN (SELECT RUN_ID, ID, PRECURSOR_ID, EXP_RT FROM FEATURE) AS FEATURE ON FEATURE_TRANSITION.FEATURE_ID = FEATURE.ID INNER JOIN PRECURSOR ON FEATURE.PRECURSOR_ID = PRECURSOR.ID INNER JOIN SCORE_TRANSITION ON FEATURE_TRANSITION.FEATURE_ID = SCORE_TRANSITION.FEATURE_ID AND FEATURE_TRANSITION.TRANSITION_ID = SCORE_TRANSITION.TRANSITION_ID INNER JOIN (SELECT ID, DECOY FROM TRANSITION) AS TRANSITION ON FEATURE_TRANSITION.TRANSITION_ID = TRANSITION.ID ORDER BY RUN_ID, PRECURSOR.ID, FEATURE.EXP_RT, TRANSITION.ID;", con)
        plot_scores(table_transition, outfile)

    con.close()

def filter_sqmass(sqmassfiles, infile, max_precursor_pep, max_peakgroup_pep, max_transition_pep):
    con = sqlite3.connect(infile)

    # process each sqmassfile independently
    for sqm_in in sqmassfiles:
        sqm_out = sqm_in.split(".sqMass")[0] + "_filtered.sqMass"

        transitions = pd.read_sql_query("SELECT TRANSITION_ID AS transition_id FROM PRECURSOR INNER JOIN FEATURE ON PRECURSOR.ID = FEATURE.PRECURSOR_ID INNER JOIN SCORE_MS1 ON FEATURE.ID = SCORE_MS1.FEATURE_ID INNER JOIN SCORE_MS2 ON FEATURE.ID = SCORE_MS2.FEATURE_ID INNER JOIN SCORE_TRANSITION ON FEATURE.ID = SCORE_TRANSITION.FEATURE_ID INNER JOIN RUN ON FEATURE.RUN_ID = RUN.ID WHERE SCORE_MS1.PEP <=" + str(max_precursor_pep) + " AND SCORE_MS2.PEP <=" + str(max_peakgroup_pep) + " AND SCORE_TRANSITION.PEP <=" + str(max_transition_pep) + " AND FILENAME LIKE '%" + sqm_in.split(".sqMass")[0] + "%';", con)['transition_id'].values

        filterChromByLabels(sqm_in, sqm_out, transitions)

