name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install system dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Build executable (Linux)
        if: runner.os == 'Linux'
        run: bash scripts/build/build_linux.sh

      - name: Build executable (Windows)
        if: runner.os == 'Windows'
        run: scripts/build/build_windows.bat

      - name: Build executable (macOS)
        if: runner.os == 'macOS'
        run: bash scripts/build/build_macos.sh

      - name: Verify artifacts (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          echo "Listing artifacts in root directory:"
          ls -lh pyprophet-*.tar.gz pyprophet-*.tar.gz.sha256 || echo "No .tar.gz files found"

      - name: Verify artifacts (Windows)
        if: runner.os == 'Windows'
        run: |
          echo "Listing artifacts in root directory:"
          Get-ChildItem -Path . -Filter "pyprophet-*.zip" | Format-Table Name, Length
          Get-ChildItem -Path . -Filter "pyprophet-*.zip.sha256" | Format-Table Name, Length
        shell: pwsh

      - name: Upload build artifacts (Linux)
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: pyprophet-linux-x86_64
          path: |
            pyprophet-linux-*.tar.gz
            pyprophet-linux-*.tar.gz.sha256
          retention-days: 7

      - name: Upload build artifacts (Windows)
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: pyprophet-windows-x86_64
          path: |
            pyprophet-windows-*.zip
            pyprophet-windows-*.zip.sha256
          retention-days: 7

      - name: Upload build artifacts (macOS)
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v4
        with:
          name: pyprophet-macos-${{ runner.arch }}
          path: |
            pyprophet-macos-*.tar.gz
            pyprophet-macos-*.tar.gz.sha256
          retention-days: 7

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Display structure of downloaded files
        run: |
          echo "Artifact directory structure:"
          find artifacts -type f -ls

      - name: Prepare release assets
        run: |
          mkdir -p release-assets
          find artifacts -type f \( -name "*.tar.gz" -o -name "*.zip" -o -name "*.sha256" \) -exec cp {} release-assets/ \;
          echo "Release assets:"
          ls -lh release-assets/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          generate_release_notes: true
          files: release-assets/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}