name: Test Build

on:
  workflow_dispatch:  # Manual trigger
  pull_request:
  push:
    branches:
      - master
      - feature/pyinstaller_packaging

jobs:
  test-build:
    name: Test build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install system dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Build executable (Linux)
        if: runner.os == 'Linux'
        run: bash scripts/build_linux.sh

      - name: Build executable (Windows)
        if: runner.os == 'Windows'
        run: scripts/build_windows.bat

      - name: Build executable (macOS)
        if: runner.os == 'macOS'
        run: bash scripts/build_macos.sh

      - name: Test executable (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          dist/pyprophet/pyprophet --help
          dist/pyprophet/pyprophet --version

      - name: Test executable (Windows)
        if: runner.os == 'Windows'
        run: |
          dist\pyprophet\pyprophet.exe --help
          dist\pyprophet\pyprophet.exe --version
